FROM centos:7.6.1810

RUN mkdir /scripts

COPY . /scripts/

RUN yum -y update

RUN yum -y install sendmail-8.14.7-5.el7.x86_64 mailx-12.5-19.el7.x86_64

WORKDIR /scripts

ENTRYPOINT /scripts/ping_check.sh
